cmake_minimum_required(VERSION 3.10)

add_executable(r1_loco_client high_level/r1_loco_client_example.cpp)
target_link_libraries(r1_loco_client unitree_sdk2)

add_executable(r1_ankle_swing_example low_level/r1_ankle_swing_example.cpp)
target_link_libraries(r1_ankle_swing_example unitree_sdk2)

add_executable(r1_audio_client_example  audio/r1_audio_client_example.cpp)
target_link_libraries(r1_audio_client_example unitree_sdk2)

add_executable(r1_A5_wrist_swing_example low_level/r1_A5_wrist_swing_example.cpp)
target_link_libraries(r1_A5_wrist_swing_example unitree_sdk2)

add_executable(r1_A7_wrist_swing_example low_level/r1_A7_wrist_swing_example.cpp)
target_link_libraries(r1_A7_wrist_swing_example unitree_sdk2)

add_executable(r1_arm_sdk_dds_example high_level/r1_arm_sdk_dds_example.cpp)
target_link_libraries(r1_arm_sdk_dds_example unitree_sdk2 fmt)

add_executable(r1_arm_action_example high_level/r1_arm_action_example.cpp)
target_link_libraries(r1_arm_action_example unitree_sdk2)

add_executable(r1_dual_arm_loco_skeleton high_level/r1_dual_arm_loco.cpp)
target_link_libraries(r1_dual_arm_loco_skeleton unitree_sdk2)

add_executable(r1_tool high_level/r1_tool.cpp)
target_link_libraries(r1_tool unitree_sdk2)
